Added friendship event
wechaty/puppet-whatsapp pull request #141
Opened 2022-02-08 12:22 UTC by guo40020

2022-02-08 12:25 UTC, bung87 requested changes

2022-02-08 12:25 UTC, bung87 commented on src/manager.ts
> +      const messages = await chat.fetchMessages({ limit: 5 })
why limit 5 ?

2022-02-08 12:25 UTC, bung87 commented on src/puppet-mixins/friendship.ts
> +  const user = this.manager.getContactById(phone)
```suggestion
  const user = await this.manager.getContactById(phone)
```

2022-02-08 12:25 UTC, bung87 commented on src/puppet-mixins/friendship.ts
> +  if ((await user).isWAContact) {
```suggestion
  if (user.isWAContact) {
```

2022-02-08 13:05 UTC, su-chang requested changes
fix eslint

2022-02-08 13:14 UTC, su-chang requested changes

2022-02-08 13:14 UTC, su-chang commented on src/manager.ts
> +    const messages = await chat.fetchMessages({ limit: 3 })
It's not a good way.

It will cost a lot time to process each message (fetch recent messages of each contact).

2022-02-08 13:14 UTC, su-chang commented on src/manager.ts
> +    if (messages.length < 2) {
`messages.length` could be 0 or not?

2022-02-08 13:14 UTC, su-chang commented on src/puppet-mixins/friendship.ts
>  export async function friendshipRawPayload (id: string): Promise<any> {
This method should be implemented.

2022-02-09 07:43 UTC, hcfw007 approved these changes

2022-02-09 07:48 UTC, su-chang requested changes
Please revert code style change.

2022-02-09 07:48 UTC, su-chang commented on src/manager.ts
> +    const isfriend = !!contactIds.find(c => c === contactId)
`include` is better

2022-02-09 07:48 UTC, su-chang commented on src/puppet-whatsapp.ts
> +    const contactId = await this.messageContact(id)
Move this logic to manager.

2022-02-09 08:22 UTC, closed without merging