fix: 🐛 use pupBrowser.isConnected to check health
wechaty/puppet-whatsapp pull request #244
Opened 2022-02-17 19:26 UTC by hcfw007

2022-02-17 19:56 UTC, bung87 approved these changes

2022-02-18 06:47 UTC, su-chang requested changes

2022-02-18 06:47 UTC, su-chang commented on src/manager.ts
> +        logger.info('will sync contact')
I think this log is useless.

2022-02-18 06:47 UTC, su-chang commented on src/manager.ts
> +        logger.info('contact synced')
ditto

2022-02-18 06:47 UTC, su-chang commented on src/manager.ts
> +    const alive = this.whatsAppClient?.pupBrowser?.isConnected()
It's better to use `this.getWhatsApp()` to get `this.whatsAppClient`.

2022-02-18 06:47 UTC, su-chang commented on src/manager.ts
> +      if (this.asystoleCount > 5) {
We should add an `CONST_VARIABLE` and `ENV` for number `5`.

2022-02-18 08:41 UTC, hcfw007 commented on src/manager.ts
> +        logger.info('will sync contact')
Indeed. I added this last night trying to find the process before ready event and forgot to remove it.

2022-02-18 08:54 UTC, su-chang approved these changes
LGTM

2022-02-18 09:10 UTC, su-chang approved these changes

2022-02-18 09:13 UTC, merged