Pr to dev
wechaty/puppet-whatsapp pull request #35
Opened 2022-01-11 09:10 UTC by wedreamer

2022-01-11 09:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/puppet-whatsapp?pullRequest=35) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/puppet-whatsapp?pullRequest=35) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/puppet-whatsapp?pullRequest=35) it.</sub>

2022-01-11 09:22 UTC, bung87 submitted a review, later dismissed

2022-01-12 02:43 UTC, wedreamer commented
## issues
[WhatsApp web api 测试及整理对应的数据结构](https://github.com/wechaty/puppet-whatsapp/issues/20)
## detail
- 测试whatsapp-web.js接口，并整理对应的请求参数及响应结果的数据结构。
- 整理测试过程中遇到的卡点（困难点），进行讨论分析。
处理相关 **repo** [whatsapp-web-examples](https://github.com/wedreamer/whatsapp-web)
- 基于整理的数据结构构建对应的 ts model。
处理相关 **this pr**

2022-01-12 13:32 UTC, bung87 requested changes

2022-01-12 13:32 UTC, bung87 commented on examples/ding-dong-bot.ts
> +      clientId: '',
any document refer to this?

2022-01-13 02:32 UTC, wedreamer commented on src/puppet-whatsapp.spec.ts
> +      // TODO: src\puppet-whatsapp.ts miss this.state.ready('on') -> puppet.state.on() === false
ok

2022-01-13 03:08 UTC, wedreamer commented on examples/ding-dong-bot.ts
> +      clientId: '',
because i used "whatsapp-web.js": "github:pedroslopez/whatsapp-web.js#multidevice"

2022-01-13 03:08 UTC, wedreamer commented on src/puppet-whatsapp.spec.ts
> +    // t.fail(e as any)
because i used "whatsapp-web.js": "github:pedroslopez/whatsapp-web.js#multidevice"

2022-01-13 04:37 UTC, bung87 submitted a review, later dismissed

2022-01-13 04:43 UTC, bung87 approved these changes

2022-01-13 04:45 UTC, merged