Start and stop
wechaty/puppet-whatsapp pull request #76
Opened 2022-01-25 02:36 UTC by su-chang

2022-01-25 02:42 UTC, wedreamer submitted a review, later dismissed

2022-01-25 02:48 UTC, windmemory requested changes
We should use verbose log for normal debugging logs, we should only use info logs when we want to inform developers what happened to the system.

2022-01-25 02:48 UTC, windmemory commented on src/manager.ts
> +    logger.info(`onAuthenticated(${JSON.stringify(session)})`)
How about only do verbose log in the whole file.

2022-01-25 02:48 UTC, windmemory commented on src/puppet-mixins/message.ts
> +import { FileBox } from 'wechaty-puppet-1.0-migration'
```suggestion
const { FileBox } = PUPPET
```

2022-01-25 02:53 UTC, huan commented on src/puppet-mixins/message.ts
> +import { FileBox } from 'wechaty-puppet-1.0-migration'
I think the best practice is to `import { FileBox} from 'file-box'` whenever it's possible because the `FileBox` resides in the `file-box` module, it's a published and stabilized API.

2022-01-25 03:32 UTC, bung87 commented on src/puppet-mixins/message.ts
> +import { FileBox } from 'wechaty-puppet-1.0-migration'
why we need `wechaty-puppet-1.0-migration` ,  this branch is only aims to `wechaty-puppet-0.41.9`

2022-01-25 03:36 UTC, su-chang commented on src/puppet-mixins/message.ts
> +import { FileBox } from 'wechaty-puppet-1.0-migration'
> why we need `wechaty-puppet-1.0-migration`? , this branch is only target to `wechaty-puppet-0.41.9`

I have change this PR base on `dev`. For `wechaty-puppet-1.0-migration`, I will create a new PR later.

2022-01-25 03:39 UTC, su-chang commented on src/manager.ts
> +    logger.info(`onAuthenticated(${JSON.stringify(session)})`)
Agree

2022-01-25 03:41 UTC, bung87 approved these changes

2022-01-27 06:47 UTC, windmemory approved these changes

2022-01-27 08:54 UTC, hcfw007 approved these changes

2022-01-27 09:25 UTC, merged